### ISSUE TITLE
address validation of bech32 address fails

### ISSUE THREAD

**Issue by willyfromtheblock** [peercoin/bitcoin_flutter#3]
`message:"tpc1qeh9ylqyhfdvkw0kclk7mul6p245a7zsamwcnkx has no matching Script"
`
bech32 addresses will be marked as invalid in the UI since Address.validateAddress will return false

**Comment by saeveritt** [comment]
The issue is here,
https://github.com/haarts/bech32/blob/master/lib/src/segwit.dart#L101

It is the bech32 dependency being used.

**Comment by saeveritt** [comment]
hotfix:
https://github.com/saeveritt/bech32

I've verified that this hotfix works. It requires a change in dependencies for bitcoin_flutter. Currently pointing it to my own repository but would prefer we perhaps publish an updated package on pub.dev 

Steps to test:

- clear pub-cache and delete pubspec.lock 
- modify bech32 dependency to the following

```
  bech32: 
    git:
      url: https://github.com/saeveritt/bech32.git
```

**Comment by peerchemist** [comment]
Can we merge in this bech32 lib into the bitcoin_flutter and make it support all encoded networks?

**Comment by haarts** [comment]
Or I could investigate and make the bech32 lib better. ;)

**Comment by willyfromtheblock** [comment]
https://blockbook.peercoin.net/tx/08e0f2ed4866a13fc072044f53403c198bb5ffc6c27960a25dd4e56c7769e34d

can confirm @saeveritt's hack works
